[package]
name = "weft"
description = "Weft command line client"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
clap = { workspace = true, features = ["string"] }
rpassword.workspace = true
tokio.workspace = true
weft-i18n.workspace = true
weft-ipc.workspace = true
