[package]
name = "weft-gui"
description = "Weft desktop app"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
arboard.workspace = true
dirs.workspace = true
notify-rust.workspace = true
russh.workspace = true
serde.workspace = true
serde_json.workspace = true
slint.workspace = true
tokio.workspace = true
ureq.workspace = true
weft-i18n.workspace = true
weft-ipc.workspace = true

[build-dependencies]
slint-build.workspace = true
